language: smalltalk
sudo: false

dist: trusty

# Select operating system(s)
os:
  - linux
  - osx


# Select compatible Smalltalk image(s)
smalltalk:
  - Pharo-stable

install: ./install-dependencies.sh

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
    fi
