language: smalltalk
sudo: false

dist: trusty

# Select operating system(s)
os:
  - linux
  - osx


# Select compatible Smalltalk image(s)
smalltalk:
  - Pharo-stable

#install: ./install-dependencies.sh

before_install:
  - |
       # Otherwise build on OSX stucks at unknown fingerprint question
       echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

       declare -r SSH_FILE="$(mktemp -u $HOME/.ssh/id_rsa.XXXX)"
       # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
       openssl aes-256-cbc -K $encrypted_10f94c58ec15_key -iv $encrypted_10f94c58ec15_iv -in travis_github_key.enc -out "$SSH_FILE" -d
       # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

       # Enable SSH authentication

       chmod 600 "$SSH_FILE" \
         && printf "%s\n" \
              "Host github.com" \
              "  IdentityFile $SSH_FILE" \
              "  LogLevel ERROR" >> ~/.ssh/config

       if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
          sudo dpkg --add-architecture i386;
          sudo apt-get update;
          export PKG_CONFIG_PATH=/usr/lib/i386-linux-gnu/pkgconfig/;

          echo "Installing c++ libraries";
          sudo apt-get install libstdc++6:i386;

          echo "Installing GTK-2.0...";
          sudo apt-get install libgtk2.0-0:i386;

          echo "Installing GTK-3.0...";
          sudo apt-get install libgtk-3-0:i386;

          echo "Installing libssl1.0.0...";
          sudo apt-get install libssl1.0.0:i386;

          echo "Installing libGL...";
          sudo apt-get install libglu1-mesa:i386;
       fi

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
    fi
