name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        sh 'git clean -fdx',
        sh 'chmod +x scripts/build/*.sh'
        sh 'scripts/build/load.sh'
