# name: CI

# on:   
#   push:
#     branches:
#       - master

# jobs:
#   build:

#     runs-on: macos-latest
    
#     steps:
#     - uses: actions/checkout@v1
#     - name: Load
#       run: |
#         chmod +x ./scripts/actions/*.sh
#         ./scripts/actions/load.sh
#       shell: bash
