name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-10.13
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        git clean -fdx
        chmod +x scripts/build/*.sh
        ./scripts/build/macLoad.sh
